name:                truth
version:             0.1.0.0
github:              "jlavelle/truth"
license:             BSD3
author:              "John C. Lavelle"
maintainer:          "jlavelle604@gmail.com"
copyright:           "2019 John C. Lavelle"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlavelle/truth#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- recursion-schemes

library:
  source-dirs: src

executables:
  truth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - truth

tests:
  truth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - truth
